network:
  host: '0.0.0.0'
  port: 19132
serverInfo:
  motd: '§aGreenFrog server'
  levelName: 'GreenFrog'
  version: '1.19.70'
  offlineMode: true
chat:
  lang: 'en_US'
  disable: false
  commandsDisabled: false
  blockInvalidMessages: true # Kicks the player if the player tried to send an too long or empty message and also prevents from using colors in chat
  commands:
    consoleCommandKick: true
    consoleCommandVer: true
    consoleCommandShutdown: true
    consoleCommandVersion: true
    consoleCommandTime: true
    consoleCommandPl: true
    consoleCommandPlugins: true
    consoleCommandStop: true # Will only stop showing in /help, if disabled
    consoleCommandSay: true
    consoleCommandOp: true
    consoleCommandDeop: true
    consoleCommandHelp: true
    consoleCommandList: true
    playerCommandVersion: false
    playerCommandPlugins: true
    playerCommandStop: true
    playerCommandSay: true
    playerCommandOp: true
    playerCommandKick: true
    playerCommandTime: true
    playerCommandDeop: true
    playerCommandList: true
    playerCommandGamemode: true
dev:
  unstable: false # Makes your server not crash on critical errors
  debug: false
  crashCode: -1
  exitCode: 0
  logUnhandledPackets: false
  defaultPermissionLevel: 2
  # Permission levels are: 
  # 4 - operator
  # 3 - unknown
  # 2 - member
  # 1 - unknown
  # 0 - visitor
  multiProtocol: false # Supports 1.19.70+. Some features may be broken
world:
  gamemode: "creative"
  worldGamemode: "creative"
  difficulty: 0
  generator: "default" # can be default, flat or void

  tickEvent: true # Should ServerTickEvent be enabled?
  tickWorldTime: true # Should time update be server side?
  tickVoid: true # Should people that are in void take damage?
  tickRegeneration: true # Should people in survival mode regenerate their health?
  tickStarvationDamage: true # Should people take damage if their food level is 0?
  randomTickSpeed: 1000
performance:
  garbageCollectorDelay: 60000