# LISTENING
# 
# This section contains the config for server host and port

host: '0.0.0.0'
port: 19132

# SERVER INFO
#
# This section contains motd, and other server info settings

motd: '§aGreenFrog server'
maxPlayers: 20
version: '1.19.70'
offlineMode: true
lang: 'en_US' # Valid languages are en_US, fr_FR, lt_LT, uk_UA, vi_VN

# CHAT
#
# This section contains some chat settings

disable: false
commandsDisabled: false
blockInvalidMessages: true # Kicks the player if the player tried to send an too long or empty message and also prevents from using colors in chat

# DEVELOPMENT SETTINGS
# 
# This section contains settings like debug, exit codes, etc

unstable: false # Makes your server not crash on critical errors
debug: false
crashCode: -1
exitCode: 0
logUnhandledPackets: false
defaultPermissionLevel: 2
# Permission levels are: 
# 4 - operator
# 3 - unknown
# 2 - member
# 1 - unknown
# 0 - visitor
multiProtocol: false # Supports 1.19.70+. Some features may be broken

# WORLD SETTINGS
#
# This section contains world settings

gamemode: "creative" # Valid gamemodes are "creative", "survival", "spectator", "adventure" and "fallback"
worldGamemode: "creative" # Valid gamemodes are "creative", "survival", "spectator", "adventure" and "fallback"
difficulty: 0 # Currently only visual
generator: "default" # Can be default, flat (superflat), or void (empty)

# COMMAND SETTINGS
# 
# Allows to disable/enable commands
# True - Means enabled
# False - Disabled

consoleCommandKick: true
consoleCommandVer: true
consoleCommandShutdown: true
consoleCommandVersion: true
consoleCommandTime: true
consoleCommandPl: true
consoleCommandPlugins: true
consoleCommandStop: true # Will only stop showing in /help, if disabled
consoleCommandSay: true
consoleCommandOp: true
consoleCommandDeop: true
consoleCommandHelp: true
consoleCommandList: true
playerCommandVersion: false
playerCommandPlugins: true
playerCommandStop: true
playerCommandSay: true
playerCommandOp: true
playerCommandKick: true
playerCommandTime: true
playerCommandDeop: true
playerCommandList: true
playerCommandGamemode: true

# PERFORMANCE SETTINGS
#
# Allows to make your server faster

garbageCollectorDelay: 60000

tickEvent: true # Should ServerTickEvent be enabled?
tickWorldTime: true # Should time update be server side?
tickVoid: true # Should people that are in void take damage?
tickRegeneration: true # Should people in survival mode regenerate their health?
tickStarvationDamage: true # Should people take damage if their food level is 0?
randomTickSpeed: 1000