name: Prettier

on:
  push:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Prettier
        run: npm install prettier
      - name: Format code
        run: npx prettier --write .
      - name: Commit changes
        run: |
          git config --global user.name "andriycraftbot"
          git config --global user.email "124494132+andriycraftbot@users.noreply.github.com"
          git add .
          git commit -m "Format code with Prettier"
          git push
  review:
    needs: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Request review
        uses: peter-evans/request-changes-action@v1.4.1
        with:
          reviewers: "andriycraft"
          number-of-reviewers: 1
          changes-requested-message: "Please review and approve changes."
