on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

permissions: write-all

jobs:
  prettier:
    if: "!contains(github.actor, 'andriycraft')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Commit changes
        run: |
          npx prettier --write .
          git config --global user.name "andriycraft"
          git config --global user.email "92477814+andriycraft@users.noreply.github.com"
          git add .
          set +e
          git status | grep modified
          if [ $? -eq 0 ]
          then
            set -e
            git commit -m "Bot: Auto builded"
            git push
          else
            set -e
            echo "No changes since last run"
          fi
