# https://peterevans.dev/posts/github-actions-how-to-automate-code-formatting-in-pull-requests/

name: auto-format
on: [pull_request, push]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: prettier
        run: npx prettier --write src/**/*.js
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name "andriycraftbot"
          git config --global user.email "124494132+andriycraftbot@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Bot: Automated changes"
          git push origin ${{ github.head_ref || github.ref_name }}
