on:
  push:
    branches:
      - main
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: Install Prettier
        run: npm install prettier
      - name: Format code
        run: npx prettier --write .
      - name: Pull latest changes
        run: git pull
      - name: Commit changes
        run: |
          git pull -r origin master
          git config --global user.name "andriycraftbot"
          git config --global user.email "124494132+andriycraftbot@users.noreply.github.com"
          git checkout -b prettier-branch
          git add .
          git commit -m "Bot: Auto builded"
          git remote add fork "https://github.com/andriycraft/GreenFrogMCBE.git"
          git push --set-upstream fork prettier-branch
          gh pr create --title "Auto builded" --body " "
