name: Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  prettier:
    if: "!contains(github.actor, 'andriycraftbot')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Commit
        run: |
          git checkout -b FORMAT_%RANDOM%
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          npm run build
          git pull
          git add .
          git commit -m "Bot: Auto builded"
          git push
          gh pr create --fill
