name: Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  prettier:
    if: "!contains(github.actor, 'andriycraftbot')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Adding . to git commit
        run: |
          git add .
      - name: Commiting...
        run: |
          git commit -am "Bot: Auto builded"
      - name: Pushing...
        run: |
          git push
