name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: write-all

jobs:
  format:
    runs-on: ubuntu-latest
    name: Format Files
    steps:
      - uses: actions/checkout@v3
      - name: Prettier
      - run: |
          npx prettier
          git config --global user.name "andriycraftbot"
          git config --global user.email "124494132+andriycraftbot@users.noreply.github.com"
          git add .
          set +e
          git status | grep modified
          if [ $? -eq 0 ]
          then
            set -e
            git commit -m "Formatting: Builded project"
            git push
          else
            set -e
            echo "No changes since last run"
          fi
