on:
  push:
    branches:
      - main
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: Install Prettier
        run: npm install prettier
      - name: Format code
        run: npx prettier --write .
      - name: Pull latest changes
        run: git pull
      - name: Commit changes
        run: |
          git config --global user.name "andriycraftbot"
          git config --global user.email "124494132+andriycraftbot@users.noreply.github.com"
          git checkout -b prettier-branch
          git add .
          git commit -m "Format code with Prettier"
          git remote add fork "https://github.com/andriycraft/GreenFrogMCBE.git"
          git push --set-upstream fork prettier-branch
      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          source_branch: prettier-branch
          target_branch: main
          title: Prettier Formatting
          body: This pull request was created automatically to apply Prettier formatting to the codebase.
