name: Build and Create PR

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Create branch
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b build_${{ github.head_ref }}
      - name: Commit
        run: |
          npm run build
          git pull
          git add .
          git commit -m "Bot: Auto builded"
          git push --set-upstream origin build_${{ github.head_ref }}
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Bot: Auto builded'
          branch: 'main'
          commit-message: 'Bot: Auto builded'
