name: Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  prettier:
    if: "!contains(github.actor, 'andriycraftbot')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Commit changes
        run: |
          npm run build
          git config --global user.name "andriycraftbot"
          git config --global user.email "124494132+andriycraftbot@users.noreply.github.com"
          git add .
          git commit -m "Bot: Auto builded"
          git push
